using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

namespace MMN.Editor
{
    /// <summary>
    /// Validates project shader declarations against generated original contracts and
    /// explicitly declared project extensions. Original contracts are generated by
    /// appdata/_re_work/dump_shader_contracts.py and must not be edited by hand.
    /// </summary>
    public static class MMNShaderContractValidator
    {
        const string ContractRoot = "Assets/MMN/Shaders/Contracts";
        const string OriginalRoot = ContractRoot + "/Original";
        const string ExtensionRoot = ContractRoot + "/Extensions";
        const string ReportRootRelative = "appdata/_re_work/shader_formalization/validation";
        const float FloatEpsilon = 0.0001f;

        static readonly MethodInfo GetPropertyAttributesMethod = typeof(Shader).GetMethod("GetPropertyAttributes");
        static readonly MethodInfo GetPropertyDefaultFloatValueMethod = typeof(Shader).GetMethod("GetPropertyDefaultFloatValue");
        static readonly MethodInfo GetPropertyDefaultVectorValueMethod = typeof(Shader).GetMethod("GetPropertyDefaultVectorValue");
        static readonly MethodInfo GetPropertyDefaultTextureNameMethod = typeof(Shader).GetMethod("GetPropertyDefaultTextureName");

        [MenuItem("Tools/MMN/Validate Shader Contracts")]
        public static void ValidateAll()
        {
            string projectRoot = Directory.GetParent(Application.dataPath).FullName;
            string originalRoot = Path.Combine(projectRoot, OriginalRoot);
            if (!Directory.Exists(originalRoot))
            {
                Debug.LogError("[MMN] Shader contract directory is missing: " + OriginalRoot);
                return;
            }

            var reports = new List<ShaderReport>();
            foreach (string path in Directory.GetFiles(originalRoot, "*.contract.json", SearchOption.TopDirectoryOnly).OrderBy(value => value, StringComparer.Ordinal))
            {
                Contract contract;
                try
                {
                    contract = JsonUtility.FromJson<Contract>(File.ReadAllText(path, Encoding.UTF8));
                }
                catch (Exception exception)
                {
                    reports.Add(ShaderReport.FromLoadFailure(Path.GetFileName(path), exception.Message));
                    continue;
                }

                if (contract == null || string.IsNullOrEmpty(contract.name))
                {
                    reports.Add(ShaderReport.FromLoadFailure(Path.GetFileName(path), "Missing contract shader name."));
                    continue;
                }

                reports.Add(ValidateContract(projectRoot, path, contract));
            }

            string outputDirectory = Path.GetFullPath(Path.Combine(projectRoot, "..", "..", ReportRootRelative));
            Directory.CreateDirectory(outputDirectory);
            string stamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
            string markdownPath = Path.Combine(outputDirectory, "shader_contract_validation_" + stamp + ".md");
            string jsonPath = Path.Combine(outputDirectory, "shader_contract_validation_" + stamp + ".json");
            File.WriteAllText(markdownPath, ToMarkdown(reports), Encoding.UTF8);
            File.WriteAllText(jsonPath, JsonUtility.ToJson(new ValidationReport { shaders = reports.ToArray() }, true), Encoding.UTF8);

            int failures = reports.Sum(report => report.Failures.Count);
            int warnings = reports.Sum(report => report.Warnings.Count);
            Debug.Log("[MMN] Shader contract validation complete: shaders=" + reports.Count
                + " failures=" + failures + " warnings=" + warnings
                + "\nMarkdown: " + markdownPath + "\nJSON: " + jsonPath);
        }

        static ShaderReport ValidateContract(string projectRoot, string contractPath, Contract contract)
        {
            var report = new ShaderReport { Shader = contract.name, Contract = ProjectRelative(projectRoot, contractPath) };
            Shader shader = Shader.Find(contract.name);
            if (shader == null)
            {
                report.Failures.Add("Missing project shader.");
                return report;
            }

            string shaderPath = AssetDatabase.GetAssetPath(shader);
            report.ShaderPath = shaderPath;
            ExtensionContract extensions = LoadExtensions(projectRoot, Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(contractPath)), contract.name, report);
            var declaredPropertyExtensions = new HashSet<string>((extensions.propertyExtensions ?? Array.Empty<ExtensionItem>())
                .Where(item => item != null && !string.IsNullOrEmpty(item.name))
                .Select(item => item.name), StringComparer.Ordinal);
            var declaredPassExtensions = new HashSet<string>((extensions.passExtensions ?? Array.Empty<ExtensionItem>())
                .Where(item => item != null && !string.IsNullOrEmpty(item.name))
                .Select(item => item.name), StringComparer.Ordinal);

            ValidateProperties(shader, contract, declaredPropertyExtensions, report);
            ValidateSourceStructure(projectRoot, shaderPath, contract, declaredPassExtensions, report);
            return report;
        }

        static ExtensionContract LoadExtensions(string projectRoot, string stem, string shaderName, ShaderReport report)
        {
            string path = Path.Combine(projectRoot, ExtensionRoot, stem + ".extensions.json");
            if (!File.Exists(path))
                return new ExtensionContract { shader = shaderName };
            try
            {
                ExtensionContract extension = JsonUtility.FromJson<ExtensionContract>(File.ReadAllText(path, Encoding.UTF8));
                if (extension == null || extension.shader != shaderName)
                {
                    report.Failures.Add("Invalid extension contract shader name: " + ProjectRelative(projectRoot, path));
                    return new ExtensionContract { shader = shaderName };
                }
                return extension;
            }
            catch (Exception exception)
            {
                report.Failures.Add("Could not load extensions: " + exception.Message);
                return new ExtensionContract { shader = shaderName };
            }
        }

        static void ValidateProperties(Shader shader, Contract contract, HashSet<string> declaredExtensions, ShaderReport report)
        {
            var expected = new Dictionary<string, OriginalProperty>(StringComparer.Ordinal);
            foreach (OriginalProperty property in contract.properties ?? Array.Empty<OriginalProperty>())
            {
                if (property == null || string.IsNullOrEmpty(property.name))
                {
                    report.Failures.Add("Original contract contains an unnamed property.");
                    continue;
                }
                expected[property.name] = property;
            }

            var actual = new Dictionary<string, int>(StringComparer.Ordinal);
            for (int index = 0; index < shader.GetPropertyCount(); index++)
                actual[shader.GetPropertyName(index)] = index;

            foreach (var pair in expected)
            {
                if (!actual.TryGetValue(pair.Key, out int index))
                {
                    report.Failures.Add("Missing original property: " + pair.Key);
                    continue;
                }
                ValidateProperty(shader, index, pair.Value, report);
            }

            foreach (var pair in actual)
            {
                if (expected.ContainsKey(pair.Key))
                    continue;
                if (declaredExtensions.Contains(pair.Key))
                    report.Extensions.Add("Property: " + pair.Key);
                else
                    report.Failures.Add("Undeclared extra property: " + pair.Key);
            }
        }

        static void ValidateProperty(Shader shader, int index, OriginalProperty expected, ShaderReport report)
        {
            ShaderPropertyType actualType = shader.GetPropertyType(index);
            if (!MatchesType(expected.type, actualType))
                report.Failures.Add("Property type mismatch " + expected.name + ": expected " + expected.type + ", actual " + actualType + ".");

            string actualDescription = shader.GetPropertyDescription(index);
            if (!string.Equals(expected.description ?? string.Empty, actualDescription ?? string.Empty, StringComparison.Ordinal))
                report.Warnings.Add("Property description mismatch (non-behavioral metadata): " + expected.name + ".");

            ValidateAttributes(shader, index, expected, report);
            ValidateDefaults(shader, index, expected, report);
        }

        static void ValidateAttributes(Shader shader, int index, OriginalProperty expected, ShaderReport report)
        {
            if (GetPropertyAttributesMethod == null)
            {
                report.Warnings.Add("Unity API does not expose property attributes: " + expected.name);
                return;
            }
            string[] actual = GetPropertyAttributesMethod.Invoke(shader, new object[] { index }) as string[] ?? Array.Empty<string>();
            string[] wanted = expected.attributes ?? Array.Empty<string>();
            if (!wanted.SequenceEqual(actual, StringComparer.Ordinal))
                report.Failures.Add("Property attributes mismatch: " + expected.name + ".");
        }

        static void ValidateDefaults(Shader shader, int index, OriginalProperty expected, ShaderReport report)
        {
            if (expected.@default == null || expected.@default.Length == 0)
                return;
            if (expected.type == "Float" || expected.type == "Range" || expected.type == "Int")
            {
                if (GetPropertyDefaultFloatValueMethod == null)
                {
                    report.Warnings.Add("Unity API does not expose scalar default: " + expected.name);
                    return;
                }
                float actual = Convert.ToSingle(GetPropertyDefaultFloatValueMethod.Invoke(shader, new object[] { index }));
                if (!Approximately(actual, expected.@default[0]))
                    report.Failures.Add("Property default mismatch: " + expected.name + ".");
                if (expected.type == "Range" && shader.GetPropertyType(index) == ShaderPropertyType.Range)
                {
                    Vector2 range = shader.GetPropertyRangeLimits(index);
                    if (!Approximately(range.x, expected.range[0]) || !Approximately(range.y, expected.range[1]))
                        report.Failures.Add("Property range mismatch: " + expected.name + ".");
                }
                return;
            }
            if (expected.type == "Color" || expected.type == "Vector")
            {
                if (GetPropertyDefaultVectorValueMethod == null)
                {
                    report.Warnings.Add("Unity API does not expose vector default: " + expected.name);
                    return;
                }
                Vector4 actual = (Vector4)GetPropertyDefaultVectorValueMethod.Invoke(shader, new object[] { index });
                if (!Approximately(actual.x, expected.@default, 0) || !Approximately(actual.y, expected.@default, 1)
                    || !Approximately(actual.z, expected.@default, 2) || !Approximately(actual.w, expected.@default, 3))
                    report.Failures.Add("Property default mismatch: " + expected.name + ".");
                return;
            }
            if (expected.type == "Texture" && GetPropertyDefaultTextureNameMethod != null)
            {
                string actual = GetPropertyDefaultTextureNameMethod.Invoke(shader, new object[] { index }) as string ?? string.Empty;
                if (!string.Equals(actual, expected.defaultTextureName ?? string.Empty, StringComparison.OrdinalIgnoreCase))
                    report.Failures.Add("Texture default mismatch: " + expected.name + ".");
            }
        }

        static void ValidateSourceStructure(string projectRoot, string shaderPath, Contract contract, HashSet<string> declaredExtensions, ShaderReport report)
        {
            string absoluteShaderPath = string.IsNullOrEmpty(shaderPath)
                ? string.Empty
                : Path.Combine(projectRoot, shaderPath);
            if (string.IsNullOrEmpty(shaderPath) || !File.Exists(absoluteShaderPath))
            {
                report.Warnings.Add("Project ShaderLab source cannot be read for Pass validation.");
                return;
            }
            string text = File.ReadAllText(absoluteShaderPath, Encoding.UTF8);
            var actual = Regex.Matches(text, "^\\s*Name\\s+\\\"([^\\\"]+)\\\"", RegexOptions.Multiline)
                .Cast<Match>().Select(match => match.Groups[1].Value).ToList();
            var expected = (contract.subShaders ?? Array.Empty<OriginalSubShader>())
                .SelectMany(item => item.passes ?? Array.Empty<OriginalPass>())
                .Select(item => item.name)
                .Distinct(StringComparer.Ordinal)
                .ToList();
            foreach (string name in expected)
                if (!actual.Contains(name))
                    report.Failures.Add("Missing original Pass: " + name);
            foreach (string name in actual)
                if (!expected.Contains(name))
                {
                    if (declaredExtensions.Contains(name))
                        report.Extensions.Add("Pass: " + name);
                    else
                        report.Failures.Add("Undeclared extra Pass: " + name);
                }
            if (actual.Count != expected.Count + declaredExtensions.Count)
                report.Warnings.Add("Pass order/count requires source review; named Pass comparison was completed.");
            ValidateOriginalSourceTokens(text, contract, report);
        }

        static void ValidateOriginalSourceTokens(string shaderLab, Contract contract, ShaderReport report)
        {
            foreach (OriginalSubShader subShader in contract.subShaders ?? Array.Empty<OriginalSubShader>())
            {
                foreach (TagEntry tag in subShader.tagEntries ?? Array.Empty<TagEntry>())
                    RequireToken(shaderLab, "\"" + tag.key + "\"\\s*=\\s*\"" + Regex.Escape(tag.value) + "\"", "Missing original SubShader Tag: " + tag.key, report);
                if (subShader.lod != 0)
                    RequireToken(shaderLab, "\\bLOD\\s+" + subShader.lod + "\\b", "Missing original SubShader LOD: " + subShader.lod, report);
                foreach (OriginalPass pass in subShader.passes ?? Array.Empty<OriginalPass>())
                {
                    foreach (TagEntry tag in pass.tagEntries ?? Array.Empty<TagEntry>())
                        RequireToken(shaderLab, "\"" + tag.key + "\"\\s*=\\s*\"" + Regex.Escape(tag.value) + "\"", "Missing original Pass Tag " + pass.name + ": " + tag.key, report);
                    ValidateBlendState(shaderLab, pass, report);
                    foreach (StateEntry state in pass.stateEntries ?? Array.Empty<StateEntry>())
                    {
                        string token = StateToken(state);
                        if (token == null)
                        {
                            report.Warnings.Add("Source parser does not yet validate Render State " + pass.name + ": " + state.key + ".");
                            continue;
                        }
                        RequireToken(shaderLab, token, "Missing original Render State " + pass.name + ": " + state.key, report);
                    }
                }
            }
        }

        static string StateToken(StateEntry state)
        {
            switch (state.key)
            {
                case "culling": return "\\bCull\\s+(?:\\[" + Regex.Escape(PropertyValue(state.value)) + "\\]|" + Regex.Escape(CullName(state.value)) + "\\b)";
                case "zWrite": return "\\bZWrite\\s+" + (state.value == "0" ? "Off" : state.value == "1" ? "On" : Regex.Escape(state.value)) + "\\b";
                case "zTest": return "\\bZTest\\s+" + Regex.Escape(ZTestName(state.value)) + "\\b";
                case "rtBlend0.srcBlend":
                case "rtBlend0.destBlend":
                    return null; // Blend needs both operands and is handled below only when known.
                default: return null;
            }
        }

        static void ValidateBlendState(string shaderLab, OriginalPass pass, ShaderReport report)
        {
            StateEntry[] states = pass.stateEntries ?? Array.Empty<StateEntry>();
            string source = FindState(states, "rtBlend0.srcBlend");
            string destination = FindState(states, "rtBlend0.destBlend");
            if (source == null || destination == null)
                return;
            string sourceToken = BlendName(source);
            string destinationToken = BlendName(destination);
            if (sourceToken == null || destinationToken == null)
            {
                report.Warnings.Add("Source parser does not yet validate Blend state " + pass.name + ".");
                return;
            }
            RequireToken(shaderLab, "\\bBlend\\s+" + sourceToken + "\\s+" + destinationToken + "\\b", "Missing original Blend state: " + pass.name, report);
        }

        static string FindState(IEnumerable<StateEntry> states, string key)
        {
            StateEntry entry = states.FirstOrDefault(item => item.key == key);
            return entry != null ? entry.value : null;
        }

        static string BlendName(string value)
        {
            if (value != null && value.StartsWith("property:", StringComparison.Ordinal))
                return "\\[" + Regex.Escape(PropertyValue(value)) + "\\]";
            switch (value)
            {
                case "0": return "Zero";
                case "1": return "One";
                case "2": return "DstColor";
                case "3": return "SrcColor";
                case "4": return "OneMinusDstColor";
                case "5": return "SrcAlpha";
                case "6": return "OneMinusSrcColor";
                case "7": return "DstAlpha";
                case "8": return "OneMinusDstAlpha";
                case "9": return "SrcAlphaSaturate";
                case "10": return "OneMinusSrcAlpha";
                default: return null;
            }
        }

        static string PropertyValue(string value)
        {
            return value != null && value.StartsWith("property:", StringComparison.Ordinal) ? value.Substring("property:".Length) : value;
        }

        static string CullName(string value)
        {
            switch (value)
            {
                case "0": return "Off";
                case "1": return "Front";
                case "2": return "Back";
                default: return value;
            }
        }

        static string ZTestName(string value)
        {
            switch (value)
            {
                case "0": return "Disabled";
                case "1": return "Never";
                case "2": return "Less";
                case "3": return "Equal";
                case "4": return "LEqual";
                case "5": return "Greater";
                case "6": return "NotEqual";
                case "7": return "GEqual";
                case "8": return "Always";
                default: return value;
            }
        }

        static void RequireToken(string text, string pattern, string failure, ShaderReport report)
        {
            if (!Regex.IsMatch(text, pattern, RegexOptions.Multiline | RegexOptions.IgnoreCase))
                report.Failures.Add(failure);
        }

        static bool MatchesType(string expected, ShaderPropertyType actual)
        {
            switch (expected)
            {
                case "Color": return actual == ShaderPropertyType.Color;
                case "Vector": return actual == ShaderPropertyType.Vector;
                case "Float": return actual == ShaderPropertyType.Float;
                case "Range": return actual == ShaderPropertyType.Range;
                case "Texture": return actual == ShaderPropertyType.Texture;
                case "Int": return actual == ShaderPropertyType.Int;
                default: return false;
            }
        }

        static bool Approximately(float actual, float[] expected, int index)
        {
            return expected != null && expected.Length > index && Approximately(actual, expected[index]);
        }

        static bool Approximately(float left, float right)
        {
            return Mathf.Abs(left - right) <= FloatEpsilon;
        }

        static string ProjectRelative(string projectRoot, string path)
        {
            return path.StartsWith(projectRoot, StringComparison.OrdinalIgnoreCase)
                ? path.Substring(projectRoot.Length + 1).Replace('\\', '/')
                : path.Replace('\\', '/');
        }

        static string ToMarkdown(List<ShaderReport> reports)
        {
            var lines = new List<string>
            {
                "# MMN Shader Contract Validation",
                "",
                "自动生成，请勿手改。",
                "",
                "| Shader | Failures | Warnings | Declared Extensions |",
                "|---|---:|---:|---:|",
            };
            foreach (ShaderReport report in reports.OrderBy(item => item.Shader, StringComparer.Ordinal))
                lines.Add("| `" + report.Shader + "` | " + report.Failures.Count + " | " + report.Warnings.Count + " | " + report.Extensions.Count + " |");
            foreach (ShaderReport report in reports.Where(item => item.Failures.Count > 0 || item.Warnings.Count > 0))
            {
                lines.Add("");
                lines.Add("## " + report.Shader);
                if (!string.IsNullOrEmpty(report.ShaderPath))
                    lines.Add("\n- Shader: `" + report.ShaderPath + "`");
                if (!string.IsNullOrEmpty(report.Contract))
                    lines.Add("- Contract: `" + report.Contract + "`");
                foreach (string failure in report.Failures)
                    lines.Add("- Failure: " + failure);
                foreach (string warning in report.Warnings)
                    lines.Add("- Warning: " + warning);
                foreach (string extension in report.Extensions)
                    lines.Add("- Extension: " + extension);
            }
            return string.Join("\n", lines) + "\n";
        }

        [Serializable] class Contract { public string name; public OriginalProperty[] properties; public OriginalSubShader[] subShaders; }
        [Serializable] class OriginalProperty { public string name; public string description; public string type; public string[] attributes; public float[] @default; public float[] range; public string defaultTextureName; }
        [Serializable] class OriginalSubShader { public int lod; public TagEntry[] tagEntries; public OriginalPass[] passes; }
        [Serializable] class OriginalPass { public string name; public TagEntry[] tagEntries; public StateEntry[] stateEntries; }
        [Serializable] class TagEntry { public string key; public string value; }
        [Serializable] class StateEntry { public string key; public string value; }
        [Serializable] class ExtensionContract { public string shader; public ExtensionItem[] propertyExtensions; public ExtensionItem[] passExtensions; }
        [Serializable] class ExtensionItem { public string name; public string reason; public string consumer; }
        [Serializable] class ValidationReport { public ShaderReport[] shaders; }

        [Serializable]
        class ShaderReport
        {
            public string Shader;
            public string ShaderPath;
            public string Contract;
            public List<string> Failures = new List<string>();
            public List<string> Warnings = new List<string>();
            public List<string> Extensions = new List<string>();

            public static ShaderReport FromLoadFailure(string shader, string failure)
            {
                var result = new ShaderReport { Shader = shader };
                result.Failures.Add(failure);
                return result;
            }
        }
    }
}
